dist: bionic

sudo: required

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - clang
      - clang-tidy
      - gcovr
      - graphviz
      - doxygen

before_script:
  - sudo sh .scripts/build-and-install-libgtest-libraries.sh

script:
  - autoreconf -vfi
  - ./configure
  - make -j`nproc --all`
  - make check
  - sudo make -j`nproc --all` install
  - # ensure a simple application can compile and link to libcrcx
  - echo 'extern void crcx_init(); int main() { crcx_init(); return 0; }' > foo.c
  - gcc -o foo foo.c `pkg-config --cflags --libs crcx`
  - # ensure a simple application can compile and link to libcrcxxx
  - echo '#include <crcx/crcxxx.h>' > foo.cpp
  - echo 'using namespace ::crcx; int main() { using Crcx = Crc<8,uint8_t,7>; Crcx crc(0,0,false,false); return 0; }' >> foo.cpp
  - g++ -o foo foo.cpp `pkg-config --cflags --libs crcxxx`

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    tags: true
  local_dir: docs/html

notifications:
  email: false
