language: cpp

dist: bionic

matrix:
  fast_finish: true
  include:
    - os: linux
      arch: amd64
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - autoconf-archive
            - cmake
            - doxygen
            - graphviz
            - lcov
      env:
        - MATRIX_EVAL="SUDO=sudo && MAKE=make && CC=gcc && CXX=g++ && CFLAGS='-Wall -Wextra -Werror' && CXXFLAGS='-Wall -Wextra -Werror'"
    - os: linux
      arch: ppc64le
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - autoconf-archive
            - cmake
      env:
        - MATRIX_EVAL="SUDO=sudo && MAKE=make && CC=gcc && CXX=g++ && CFLAGS='-Wall -Wextra -Werror' && CXXFLAGS='-Wall -Wextra -Werror'"
    - os: linux
      arch: s390x
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - autoconf-archive
            - cmake
      env:
        - MATRIX_EVAL="SUDO=sudo && MAKE=make && CC=gcc && CXX=g++ && CFLAGS='-Wall -Wextra -Werror' && CXXFLAGS='-Wall -Wextra -Werror'"
    - os: linux
      arch: arm64
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - autoconf-archive
            - cmake
      env:
        - MATRIX_EVAL="SUDO=sudo && MAKE=make && CC=gcc && CXX=g++ && CFLAGS='-Wall -Wextra -Werror' && CXXFLAGS='-Wall -Wextra -Werror'"
    - os: linux
      arch: amd64
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - autoconf-archive
            - cmake
            - clang
      env:
        - MATRIX_EVAL="SUDO=sudo && MAKE=make && CC=clang && CXX=clang++ && CFLAGS='-Wall -Wextra -Werror' && CXXFLAGS='-Wall -Wextra -Werror'"
    - os: linux
      arch: ppc64le
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - autoconf-archive
            - cmake
            - clang
      env:
        - MATRIX_EVAL="SUDO=sudo && MAKE=make && CC=clang && CXX=clang++ && CFLAGS='-Wall -Wextra -Werror' && CXXFLAGS='-Wall -Wextra -Werror'"
    - os: linux
      arch: s390x
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - autoconf-archive
            - cmake
            - clang
      env:
        - MATRIX_EVAL="SUDO=sudo && MAKE=make && CC=clang && CXX=clang++ && CFLAGS='-Wall -Wextra -Werror' && CXXFLAGS='-Wall -Wextra -Werror'"
    - os: linux
      arch: arm64
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - autoconf-archive
            - cmake
            - clang
      env:
        - MATRIX_EVAL="SUDO=sudo && MAKE=make && CC=clang && CXX=clang++ && CFLAGS='-Wall -Wextra -Werror' && CXXFLAGS='-Wall -Wextra -Werror'"
    - os: osx
      osx_image: xcode11.3
      addons:
        homebrew:
          packages:
            - autoconf-archive
      env:
        - MATRIX_EVAL="SUDO=sudo && MAKE=make"
    - os: windows
  allow_failures:
  - os: windows
    if: tag IS blank
  - os: osx
    if: tag IS blank

before_install:
- |-
    case $TRAVIS_OS_NAME in
      linux)
        eval "${MATRIX_EVAL}"
        ;;
      osx)
        eval "${MATRIX_EVAL}"
        ;;
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export MAKE=mingw32-make  # so that Autotools can find it

        #
        # https://travis-ci.community/t/autoconf-automake/964/4
        #
        
        wget -nv https://master.dl.sourceforge.net/project/mingw/MSYS/Base/msys-core/msys-1.0.19-1/msysCORE-1.0.19-1-msys-1.0.19-bin.tar.xz
        wget -nv https://master.dl.sourceforge.net/project/mingw/MSYS/Extension/m4/m4-1.4.16-2/m4-1.4.16-2-msys-1.0.17-bin.tar.lzma

        mkdir /mingw
        xz -d msysCORE-1.0.19-1-msys-1.0.19-bin.tar.xz
        tar -C /mingw -xf msysCORE-1.0.19-1-msys-1.0.19-bin.tar

        xz -d  m4-1.4.16-2-msys-1.0.17-bin.tar.lzma
        tar -C /mingw -xf m4-1.4.16-2-msys-1.0.17-bin.tar

        # Msys autoconf, automake, libtool

        +wget -nv https://master.dl.sourceforge.net/project/mingw/MinGW/Extension/autoconf/autoconf2.5/autoconf2.5-2.68-1/autoconf2.5-2.68-1-mingw32-bin.tar.lzma
        wget -nv https://master.dl.sourceforge.net/project/mingw/MinGW/Extension/automake/automake1.11/automake1.11-1.11.1-1/automake1.11-1.11.1-1-mingw32-bin.tar.lzma
        wget -nv https://master.dl.sourceforge.net/project/mingw/MinGW/Extensionlibtool/libtool-2.4-1/libtool-2.4-1-mingw32-bin.tar.lzma

        xz -d autoconf2.5-2.68-1-mingw32-bin.tar.lzma
        xz -d automake1.11-1.11.1-1-mingw32-bin.tar.lzma
        xz -d libtool-2.4-1-mingw32-bin.tar.lzma

        tar -C /mingw -xf autoconf2.5-2.68-1-mingw32-bin.tar
        tar -C /mingw -xf automake1.11-1.11.1-1-mingw32-bin.tar
        tar -C /mingw -xf libtool-2.4-1-mingw32-bin.tar

        # Add aliases to standard names
        ln -sf /mingw/bin/aclocal-1.11 /mingw/bin/aclocal
        ln -sf /mingw/bin/automake-1.11 /mingw/bin/automake
        ln -sf /mingw/bin/autoconf-2.68 /mingw/bin/autoconf
        ln -sf /mingw/bin/autoheader-2.68 /mingw/bin/autoheader
        ln -sf /mingw/bin/autom4te-2.68 /mingw/bin/autom4te
        ln -sf /mingw/bin/autoreconf-2.68 /mingw/bin/autoreconf
        ln -sf /mingw/bin/autoscan-2.68 /mingw/bin/autoscan
        ln -sf /mingw/bin/autoupdate-2.68 /mingw/bin/autoupdate
        ln -sf /mingw/bin/ifnames-2.68 /mingw/bin/ifnames
        ln -sf /mingw/bin/m4 /usr/bin/m4

        # Fix the environment for autotools to actually work
        ln -s /c/tools/msys64/usr/share/autoconf* /usr/share/
        ln -s /c/tools/msys64/usr/share/automake* /usr/share/
        ln -s /c/tools/msys64/usr/share/aclocal* /usr/share/
        ln -s /c/tools/msys64/usr/share/libtool* /usr/share/
        ln -s /c/tools/msys64/usr/share/pkgconfig /usr/share/
        ln -s /c/tools/msys64/usr/bin/autom4te /usr/bin/
        ln -s /c/tools/msys64/usr/bin/autoconf /usr/bin/
        ln -s /c/tools/msys64/usr/bin/autoheader /usr/bin/
        ln -s /c/tools/msys64/usr/bin/m4 /usr/bin/

        PATH=$PATH:/c/tools/msys64/usr/bin/
        export CONFIG_SHELL=/usr/bin/bash.exe
        export PATH=/c/tools/msys64/usr/bin/:$PATH
        ;;
    esac

before_cache:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64

before_script:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then ${SUDO} sh .scripts/build-and-install-libgtest-libraries.sh; fi

script:
  - autoreconf -vfi
  - ./configure ${OPTS}
  - make -j`nproc --all`
  - make check
  - ${SUDO} ${MAKE} -j`nproc --all` install
  - # ensure a simple application can compile and link to libcrcx
  - echo 'extern void crcx_init(); int main() { crcx_init(); return 0; }' > foo.c
  - ${CC} -o foo foo.c `pkg-config --cflags --libs crcx`
  - # ensure a simple application can compile and link to libcrcxxx
  - echo '#include <crc3x/crc3x.h>' > foo.cpp
  - echo 'using namespace ::crc3x; int main() { using Crc3x = Crc<uint8_t,8,7>; Crc3x crc(0,0,false,false); return 0; }' >> foo.cpp
  - ${CXX} -std=c++17 -o foo foo.cpp `pkg-config --cflags --libs crc3x`

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    tags: true
    condition:
      - $TRAVIS_OS_NAME = linux
      - $TRAVIS_CPU_ARCH = amd64
  local_dir: docs/html

notifications:
  email: false
