dist: bionic

sudo: required

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - clang
      - clang-tidy
      - gcovr
      - graphviz
      - doxygen

before_script:
  - sudo sh .scripts/build-and-install-libgtest-libraries.sh

script:
  - autoreconf -vfi
  - ./configure
  - make -j`nproc --all`
  - make check
  - sudo make -j`nproc --all` install
  - # ensure a simple application can compile and link to libcrcx
  - echo 'extern void crcx_init(); int main() { crcx_init(); return 0; }' > foo.c
  - gcc -o foo foo.c `pkg-config --cflags --libs crcx`

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    tags: true
  local_dir: docs/html

notifications:
  email: false
