dist: bionic

sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - clang
      - clang-tidy
      - gcovr
      - graphviz
      - doxygen

before_script:
  - sudo sh .scripts/build-and-install-libgtest-libraries.sh

script:
  - autoreconf -vfi
  - ./configure
  - make -j`nproc --all`
  - make check

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    tags: true
  local_dir: docs/html

notifications:
  email: false
