dist: bionic

sudo: required

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - autoconf-archive
      - clang
      - clang-tidy
      - cmake
      - doxygen
      - graphviz
      - lcov

before_script:
  - sudo sh .scripts/build-and-install-libgtest-libraries.sh

script:
  - autoreconf -vfi
  - ./configure --enable-code-coverage
  - make -j`nproc --all`
  - make check
  - sudo make -j`nproc --all` install
  - # ensure a simple application can compile and link to libcrcx
  - echo 'extern void crcx_init(); int main() { crcx_init(); return 0; }' > foo.c
  - gcc -o foo foo.c `pkg-config --cflags --libs crcx`
  - # ensure a simple application can compile and link to libcrcxxx
  - echo '#include <crc3x/crc3x.h>' > foo.cpp
  - echo 'using namespace ::crc3x; int main() { using Crc3x = Crc<uint8_t,8,7>; Crc3x crc(0,0,false,false); return 0; }' >> foo.cpp
  - g++ -o foo foo.cpp `pkg-config --cflags --libs crc3x`

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    tags: true
  local_dir: docs/html

notifications:
  email: false
